<?php

class FageBridge extends XPathAbstract {
    const NAME = 'FageBridge';
    const URI = 'https://www.fage.org/';
    const DESCRIPTION = 'Fédération des Associations Générales Etudiantes';
    const MAINTAINER = 'StelFux';
/*
    const PARAMETERS = array(
        array(
            'newsType' => array(
                'name' => 'newsType',
                'type' => 'string',
                'required' => true,
                'values' => array(
                    'Actualités de la FAGE et de ses Fédérations' => 'actualites-fage-federations'
                )
            )
        )
    );
*/
    /**
     * Source Web page URL (should provide either HTML or XML content)
     * @return string
     */
    protected function getSourceUrl() {
        return "https://www.fage.org/news/actualites-fage-federations/";
        // return $this->encodeUri($this->getURI() . 'news/actualites-fage-federations/');
        //return $this->encodeUri($this->getURI() . 'news/' . $this->getInput('newsType') . '/');
    }

    const XPATH_EXPRESSION_FEED_ICON = './/link[@rel="shortcut icon"]/@href';
    const XPATH_EXPRESSION_ITEM = '//div[@class="core"]/ul/li/a';
    const XPATH_EXPRESSION_ITEM_TITLE = './h3[@class="h3"]';
    const XPATH_EXPRESSION_ITEM_CONTENT = './div/p';
    const XPATH_EXPRESSION_ITEM_URI = './@href';
    const XPATH_EXPRESSION_ITEM_TIMESTAMP = './p[@class="date"]';
    const XPATH_EXPRESSION_ITEM_ENCLOSURES = './/img/@src';
    const XPATH_EXPRESSION_ITEM_CATEGORIES = './p/span';


    /**
     * Formats the timestamp of a feed item. Takes extracted raw timestamp and returns unix
     * timestamp as integer.
     * Can be easily overwritten for example if a special format has to be expected on the
     * source website.
     * @param string $value
     * @return false|int
     */
    protected function formatItemTimestamp($value) {
        $value = str_replace('/', '-', $value);
        return strtotime($value);
    }

    protected function formatItemCategories($value)
    {
        return explode(', ', $value); // TODO: Change the autogenerated stub
    }
}
